### Tensor
- 텐서는 행렬이나 배열과 매우 유사한 구조를 가짐
- PyTorch에서는 텐서를 사용하여 입출력과 매개변수들을 encode 함
- tensor와 NumPy 배열은 종종 동일한 내부 메모리를 공유할 수 있음 -> 데이터 복사할 필요가 없음

In [1]:
import torch
import numpy as np

#### Tensor 초기화
- 텐서는 여러 방법으로 초기화 할 수 있음
1. 데이터로부터 직접 생성하기
    - 데이터로부터 직접 생성이 가능함 -> 데이터의 자료형은 자동으로 유추
2. NumPy 배열로부터 생성하기
    - 텐서는 NumPy 배열로 생성할 수 있음 -> 반대도 가능
3. 다른 텐서로부터 생성하기
    - 명시적으로 override 하지 않으면, 인자로 주어진 텐선의 shape과 datatype 유지
4. 무작위 또는 상수 값을 사용하기
    - `shape`은 텐서의 차원을 나타내는 튜플

In [2]:
# 데이터로부터 직접 생성하기
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
# NumPy 배열로부터 생성하기 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
# 다른 텐서로부터 생성하기
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4015, 0.7727],
        [0.9413, 0.1714]]) 



In [6]:
# 무작위 또는 상수 값을 사용하기
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor}")

Random Tensor: 
tensor([[0.4187, 0.0547, 0.2847],
        [0.1225, 0.1583, 0.5319]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 Attribute
- 텐서의 속성은 텐서의 shape, datatype 및 어느 장치에 저장되는지를 나타넴(device)

In [7]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 텐서의 연산
- 100가지 이상의 연산을 수행할 수 있음
- 각 연산들은 GPU에서 실행할 수 있음
- 기본적으로 텐서는 CPU에 생성됨 -> `.to` 메소드를 사용하면 GPU로 텐서를 명시적으로 이동할 수 있음
     - 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 발생

In [8]:
# GPU 사용이 가능하면 텐서를 이동하는 코드
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [9]:
# NumPy 식 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# tensor 합치기
# torch.cat 함수는 주어진 차원(dim)을 따라 여러 텐서를 연결(concatenate)함
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# 산술 연산
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T) # tensor.T는 텐서의 전치를 반환

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
# 단일-요소 텐서
# 텐서의 모든 값을 하나로 집계하여 요소가 하나인 경우 item()을 사용하여 Python 숫자 값으로 변환할 수 있음
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [14]:
# 바꿔치기 연산 (in-place)
# 연산 결과를 피연산자에(operand)에 저장하는 연산을 바꿔치기 연산이라고 함
# _ 접미사를 갖음
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NumPy 변환
- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유
- 따라서 하나를 변경하면 다른 하나도 변경된다

In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [16]:
# tensor에 1을 더하면 numpy 배열에도 반영됨
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [17]:
# NumPy arrays를 tensor로 변환
n = np.ones(5)
t = torch.from_numpy(n)

In [18]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
